[project]
name = "pinns"
version = "0.1.0"
description = "Physics Informed Neural Networks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "scipy>=1.15.3",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "poethepoet>=0.46.0",
    "pre-commit>=4.6.0",
    "ruff>=0.15.15",
    "scipy-stubs>=1.15.3.0",
    "torch>=2.12.0", # For dev checks, use version on server for runtime
]

[tool.ruff]
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.poe.tasks]
_format = "ruff format ."
_clean = "ruff check --fix ."
format.sequence = ["_format", "_clean"]

_type = "mypy ."
_check = "ruff check ."
lint.sequence = ["_type", "_check"]

pip = "uv pip compile pyproject.toml -o requirements.txt"
setup = "pre-commit install"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pinns"]
